name: tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Checkout add-on repo
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          python -m pip install -r ./requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run mypy
        run: mypy
